-- BeSpoke — V3: user profile fields, designer profile view counter, reviews.
-- Idempotent DDL: the live DB may already have parts of this applied (ddl-auto: update).

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url character varying(1000);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone character varying(30);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS city character varying(120);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;

ALTER TABLE public.designer_profiles ADD COLUMN IF NOT EXISTS view_count bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designer_id bigint NOT NULL REFERENCES public.users(id),
    customer_id bigint NOT NULL REFERENCES public.users(id),
    lead_id bigint REFERENCES public.leads(id),
    rating int NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment character varying(2000),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (designer_id, customer_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_designer_id ON public.reviews (designer_id);
CREATE INDEX IF NOT EXISTS idx_reviews_customer_id ON public.reviews (customer_id);
